CREATE TABLE dbo.EMPLOYEE(
	E_DNI					        varchar(15) NOT NULL,
	E_FIRSTNAME					    varchar(50) NOT NULL,
	E_LASTNAME					    varchar(50) NOT NULL,
	E_FK_COMPANY				    int,
	CONSTRAINT PK_DNI_EMP PRIMARY KEY (E_DNI)
);

CREATE TABLE dbo.COMPANY(
	C_CODE					int NOT NULL,
	C_COMPANY_NAME			varchar(50) NOT NULL,
	CONSTRAINT PK_COMPANY_CODE PRIMARY KEY (C_CODE)
);

CREATE TABLE dbo.ASSIGNMENT(
	A_CODE					        int NOT NULL,
	A_HEADER					    varchar(75) NOT NULL,
	A_DESCRIPTION					varchar(250) NOT NULL,
    A_DATE                          date NOT NULL,
    A_TYPE                          varchar(20) NOT NULL,
	A_FK_EMPLOYEE					int,
	CONSTRAINT PK_ASSIGNMENT PRIMARY KEY (A_CODE),
	CONSTRAINT CH_ASSIGNMENT CHECK(A_TYPE in('Tarea', 'Incidencia'))
);

ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_EMPLOYEE_COMPANY
FOREIGN KEY(E_FK_COMPANY)
REFERENCES COMPANY(C_CODE) ON DELETE SET NULL;

ALTER TABLE ASSIGNMENT
ADD CONSTRAINT FK_EMPLOYEE_ASSIGNMENT
FOREIGN KEY(A_FK_EMPLOYEE)
REFERENCES EMPLOYEE(E_DNI) ON DELETE SET NULL;

SELECT TOP(1) COUNT(E.E_DNI) AS HITS, E.E_DNI, E.E_FIRSTNAME, E.E_LASTNAME FROM EMPLOYEE E, COMPANY C, ASSIGNMENT A
WHERE C.C_COMPANY_NAME = 'Mutiny' AND A.DATE BETWEEN '2021-05-01' AND '2021-05-31' AND E.E_FK_COMPANY = C.C_CODE AND A.A_FK_EMPLOYEE = E.E_DNI
GROUP BY E.E_DNI
ORDER BY HITS DESC;